- src/utils.js
Obviously not ideal -- it should be extracted into a shared library, but that is not today.
> copy part of utils.js from serviceprovider

- src/__tests__/app.test.js
- src/app.js
- src/oauth/configstore/__tests__/inmemory.test.js
- src/oauth/configstore/inmemory.js
- src/oauth/tokenstore/inmemory.js
> return config based on userId, libraryId and clientId

- src/utils.js
> use Object.assign instead of lodash.merge

- src/__tests__/app.test.js
- src/expressapp.js
- src/oauth/twolevel.model.js
> disallow login with client credentials

- src/expressapp.js
> only accept post-requests when requesting a token

- src/oauth/twolevel.model.js
> remove references to borchk from twolevel.model.js

- src/__tests__/app.test.js
- src/__tests__/utils.test.js
- src/app.js
- src/expressapp.js
- src/oauth/userstore/__tests__/borchk.test.js
- src/oauth/userstore/__tests__/userstore.test.js
- src/oauth/userstore/borchk.js
- src/oauth/userstore/inmemory.js
- src/utils.js
> add support for login with anonymous users

- src/expressapp.js
- src/oauth/twolevel.model.js
Should be enabled again when #62 is fixed
> disable throttling for now

- src/app.js
- src/expressapp.js
> change default config location

- src/app.js
- src/expressapp.js
> split smaug into two express apps

- src/expressapp.js
> set default access token lifetime to 30 days

- examples/config/inmemory-config.json
- src/__tests__/app.test.js
- src/app.js
- src/oauth/clientstore/__tests__/clientstore.test.js
- src/oauth/clientstore/inmemory.js
- src/oauth/configstore/__tests__/inmemory.test.js
- src/oauth/tokenstore/__tests__/tokenstore.test.js
- src/oauth/tokenstore/inmemory.js
- src/oauth/tokenstore/redis.js
> factor clientstore out of tokenstore

- src/__tests__/app.test.js
- src/app.js
- src/expressapp.js
- src/oauth/tokenstore/__tests__/tokenstore.test.js
- src/oauth/tokenstore/inmemory.js
- src/oauth/tokenstore/redis.js
- src/oauth/twolevel.model.js
> erase tokenstore's knowledge of clientstore

- src/__tests__/app.test.js
- src/app.js
- src/expressapp.js
- src/oauth/clientstore/__tests__/clientstore.test.js
- src/oauth/clientstore/inmemory.js
- src/oauth/configstore/__tests__/inmemory.test.js
- src/oauth/configstore/inmemory.js
- src/oauth/tokenstore/__tests__/tokenstore.test.js
- src/oauth/tokenstore/inmemory.js
- src/oauth/tokenstore/redis.js
- src/oauth/twolevel.model.js
- src/oauth/userstore/__tests__/borchk.test.js
- src/oauth/userstore/__tests__/userstore.test.js
- src/oauth/userstore/borchk.js
- src/oauth/userstore/inmemory.js
> add admin app skeleton and perform general code cleanup \o/

- examples/config/inmemory-config.json
- package.json
- src/__tests__/admin.test.js
- src/expressapp.js
> implement basic auth with hardcoded users in config-file

- examples/config/inmemory-config.json
- package.json
- src/__tests__/admin.test.js
- src/__tests__/app.test.js
- src/expressapp.js
- src/oauth/clientstore/__tests__/clientstore.test.js
- src/oauth/clientstore/inmemory.js
> implement basic manipulation of clients over http

- src/oauth/tokenstore/redis.js
> make redis tokenstore configurable

- src/__tests__/app.test.js
- src/expressapp.js
- src/oauth/configstore/__tests__/inmemory.test.js
- src/oauth/configstore/inmemory.js
fixes #86 
```
$ curl -sSL "http://localhost:3001/configuration?token=qwerty" | jq '.user'
{
"id": "donald",
"libraryId": "010101"
}
```
> add user details to context

- src/__tests__/app.test.js
- src/expressapp.js
> fix wrong status code by moving oauth error handler last in the list

- README.md
- src/expressapp.js
> add endpoint to dump config

- src/expressapp.js
> implement healthcheck that pings each store

- src/oauth/configstore/__tests__/dbc.test.js
- src/oauth/configstore/dbc.js
> create dbc specific configstore, inhering from inmemory, that injects agencyid into each section where it's missing

- package.json
- src/expressapp.js
> return 404 on token-not-found, and log errors as json

- src/__tests__/endpoints.test.js
> test that /configuration and /clients are only available on the proper ports

- src/expressapp.js
> enable cors on oauth endpoint

- src/expressapp.js
> cors: allow authorization header

- src/__tests__/app.test.js
- src/expressapp.js
- src/oauth/configstore/__tests__/dbc.test.js
- src/oauth/configstore/dbc.js
> support new dbc config format along with the current format

- src/oauth/twolevel.model.js
> don't throw error on invalid credentials

- src/oauth/userstore/borchk.js
> reject promise with error instead of just returning an error

- src/expressapp.js
- src/utils.js
> 129 access log

- src/__tests__/app.test.js
- src/expressapp.js
- src/oauth/configstore/__tests__/dbc.test.js
- src/oauth/configstore/dbc.js
> remove code related to context v1 and v2

- src/expressapp.js
> log query parameters

- src/expressapp.js
> change the not-so-helpfull text to a link to the github repo

- src/oauth/configstore/dbc.js
> make it possible to override search.profile for an agency

- package.json
- src/oauth/clientstore/postgres.js
- src/oauth/configstore/__tests__/dbc.test.js
- src/oauth/configstore/dbc.js
> configstore and caching.

- src/__tests__/admin.test.js
- src/models/clients.js
- src/oauth/clientstore/__tests__/clientstore.test.js
- src/oauth/clientstore/inmemory.js
- src/oauth/clientstore/postgres.js
> make all clientstore backends generate the secret

- src/expressapp.js
> Add method to admin api for creating new tokens for clients

- src/oauth/configstore/dbc.js
for use instead of lodash equivalent.
> #181: Create new defaultsDeep method

- src/migrations/20180116085847-add-cascade-on-delete.js
> Add Cascade on delete to foreign key

- src/__tests__/app.test.js
- src/expressapp.js
> ISIL working with anonymous login

- src/oauth/userstore/borchk.js
> log error if borchk fails

- Dockerfile
- Jenkinsfile
- examples/config/config-stg.json
- package.json
Created and modified Dockerfile and Jenkinsfile
> 245 docker til smaug niw

- src/oauth/userstore/borchk.js
Makes it possible to use borchk v2.5
> Dont use borchk for anonymous tokens

- package-lock.json
- package.json
- src/config/config.js
part of [SP-1039]
[SP-1039]: https://dbcjira.atlassian.net/browse/SP-1039
> Update opensearch and openformat

- src/config/config.js
løser issue: https://dbcjira.atlassian.net/browse/SMAUG-269?jql=labels%20in%20(PHP7MIG%2C%20php7MIG)
> OpenUserStatus 1.9 --> 2.0

- Jenkinsfile
- docker-compose-cypress.yml
- package-lock.json
- package.json
- src/config/config.js
This pull request also fixes issue with running database with docker-compose without a password and makes security updates
> Change performance url

- src/config/config.js
løser issue: SMAUG-273
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=71&projectKey=FE2&modal=detail&selectedIssue=SMAUG-273
> Add holdingsitems url to default config

- src/config/config.js
Changed recommender to `http://booklens-190101-1-0.mi-prod.svc.cloud.dbc.dk/`
> Recommender: recomole to booklens

- src/config/config.js
https://dbcjira.atlassian.net/secure/RapidBoard.jspa?rapidView=169&modal=detail&selectedIssue=SP-1063
> Add 'workpresentation' to smaug default config

- src/lib/culr/culr.client.js
Parameter change for getAccountsByGlobalId
> #SMAUG-286 use CULR 1.6

- docker-compose-cypress.yml
- package-lock.json
- package.json
- src/app.js
- src/expressapp.js
- src/oauth/tokenstore/__tests__/tokenstore.test.js
- src/throttle/throttle.js
redis platformdb-[sp]01 will close and frontend-[staging|prod]-redis-cluster.platform-redis.svc.cloud.dbc.dk should be used
> SMAUG-287 Use ioredis to support redis cluster
